monitor.bluez.rules = [
  {
    matches = [
      {
        ## Esto aplica a todos los dispositivos bluetooth
        device.name = "~bluez_card.*"
      }
    ],
    actions = {
      update-props = {
        ## Evita que Zoom fuerce el cambio a perfiles de baja calidad
        bluez5.roles = [ a2dp_sink a2dp_source ]
      }
    }
  }
]
