monitor = , preferred, auto, 1

exec-once = regreet ; hyprctl dispatch exit

input {
    kb_layout = latam
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    no_cursor_warps = true
    no_focus_fallback = true
    resize_on_border = false
    hover_icon_on_border = false
    layout = master
}

decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    disable_autoreload = true
    disable_hyprland_logo = true
}
