require("config.monitors")
require("config.environment")
require("config.settings")
require("config.autostart")
require("config.bindings")
require("config.windowrules")
require("config.animations")
require("config.workspaces")
