hl.curve("default", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1 } } })
hl.curve("snappy", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "windows", enabled = true, speed = 8, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 8, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 8, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "snappy", style = "slidefade 20%" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 5, bezier = "snappy", style = "slidefade 20%" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 5, bezier = "snappy", style = "slidefade 20%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
